import React from "react";
import type { OptimisationGridResult, PairedForwardResult } from "../../types";
import { CollapsibleSection } from "../collapsible-section";

export function OptimisationEvidence({ path, mode, result, filter, sort, inputRef, enabled, onPathChange, onModeChange, onSelect, onRun, onFilterChange, onSortChange }: {
  path: string; mode: string; result: OptimisationGridResult | null; filter: string; sort: string; inputRef: React.RefObject<HTMLInputElement | null>; enabled: boolean;
  onPathChange: (value: string) => void; onModeChange: (value: string) => void; onSelect: (event: React.ChangeEvent<HTMLInputElement>) => void; onRun: () => void; onFilterChange: (value: string) => void; onSortChange: (value: string) => void;
}): React.ReactElement {
  const rows = result === null ? [] : result.rows.filter((row) => Object.values(row).some((value) => value.toLowerCase().includes(filter.trim().toLowerCase()))).sort((left, right) => String(left[sort] ?? "").localeCompare(String(right[sort] ?? ""), undefined, { numeric: true }));
  return <CollapsibleSection title="Optimisation parameter-grid evidence">
    <p className="trl-m0__note">Imports the selected MT5 XML exactly as reported. It never selects a best pass, recomputes MT5 metrics, or makes robustness, portfolio, broker, or live-trading claims.</p>
    <label className="trl-m0__field"><span>MT5 parameter-optimisation XML</span><input value={path} onChange={(event) => onPathChange(event.currentTarget.value)} placeholder="C:\\path\\to\\parameter_optimisation.xml" /></label>
    <div className="trl-m0__actions"><input ref={inputRef} className="trl-m0__file-input" type="file" accept=".xml,text/xml,application/xml" onChange={onSelect} /><button type="button" onClick={() => inputRef.current?.click()}>Browse XML…</button></div>
    <label className="trl-m0__field"><span>Modelling mode — USER_SUPPLIED</span><input value={mode} onChange={(event) => onModeChange(event.currentTarget.value)} /></label>
    <p className="trl-m0__note">The XML does not establish this setting. It is recorded as your declaration; use “1-minute OHLC” for this export.</p>
    <button type="button" className="mod-cta" disabled={!enabled} onClick={onRun}>Import parameter-grid evidence</button>
    {result && <section className="trl-m0__analysis-result"><h4>Qualified parameter-grid evidence</h4><dl className="trl-m0__diagnostic-grid"><dt>Source / snapshot</dt><dd><code>{result.source.filename}</code>; <code>{result.source.sha256}</code></dd><dt>Passes / input columns</dt><dd>{result.pass_count}; {result.parameter_columns.join(", ")}</dd><dt>Declared modelling mode</dt><dd><code>{result.adapter.modelling_mode}</code> — {result.adapter.modelling_mode_source}</dd><dt>Tester title</dt><dd>{result.report_metadata.Title}</dd><dt>Artifact</dt><dd><code>{result.artifacts.table}</code></dd><dt>Limitations</dt><dd>{result.warnings.join(" ")}</dd></dl><div className="trl-m0__scenario-fields"><label className="trl-m0__field"><span>Filter pass values</span><input value={filter} onChange={(event) => onFilterChange(event.currentTarget.value)} placeholder="Optional text" /></label><label className="trl-m0__field"><span>Sort for inspection</span><select value={sort} onChange={(event) => onSortChange(event.currentTarget.value)}>{result.headers.map((header) => <option key={header} value={header}>{header}</option>)}</select></label></div><div className="trl-m0__optimisation-table"><table><thead><tr>{result.headers.map((header) => <th key={header}>{header}</th>)}</tr></thead><tbody>{rows.map((row) => <tr key={row.trl_pass_id}>{result.headers.map((header) => <td key={header}>{row[header]}</td>)}</tr>)}</tbody></table></div><p className="trl-m0__note">Showing {rows.length} of {result.pass_count} passes. Sorting/filtering is inspection only; no parameter has been selected.</p></section>}
  </CollapsibleSection>;
}

export function PairedForwardEvidence({ inPath, forwardPath, inStart, inEnd, forwardStart, forwardEnd, mode, result, inRef, forwardRef, onInPathChange, onForwardPathChange, onInStartChange, onInEndChange, onForwardStartChange, onForwardEndChange, onModeChange, onInSelect, onForwardSelect, onRun }: {
  inPath: string; forwardPath: string; inStart: string; inEnd: string; forwardStart: string; forwardEnd: string; mode: string; result: PairedForwardResult | null; inRef: React.RefObject<HTMLInputElement | null>; forwardRef: React.RefObject<HTMLInputElement | null>;
  onInPathChange: (value: string) => void; onForwardPathChange: (value: string) => void; onInStartChange: (value: string) => void; onInEndChange: (value: string) => void; onForwardStartChange: (value: string) => void; onForwardEndChange: (value: string) => void; onModeChange: (value: string) => void; onInSelect: (event: React.ChangeEvent<HTMLInputElement>) => void; onForwardSelect: (event: React.ChangeEvent<HTMLInputElement>) => void; onRun: () => void;
}): React.ReactElement {
  const headers = result === null ? [] : Object.keys(result.rows[0] ?? {});
  return <CollapsibleSection title="Paired forward evidence">
    <p className="trl-m0__note">Pairs source-reported MT5 results by the complete EA input signature. It is evidence comparison only: no best-pass selection, score, threshold, recommendation, or .set export.</p>
    <label className="trl-m0__field"><span>In-sample optimisation XML</span><input value={inPath} onChange={(event) => onInPathChange(event.currentTarget.value)} placeholder="C:\\path\\to\\in_sample.xml" /></label><div className="trl-m0__actions"><input ref={inRef} className="trl-m0__file-input" type="file" accept=".xml" onChange={onInSelect} /><button type="button" onClick={() => inRef.current?.click()}>Browse in-sample XML…</button></div>
    <label className="trl-m0__field"><span>Forward-results XML</span><input value={forwardPath} onChange={(event) => onForwardPathChange(event.currentTarget.value)} placeholder="C:\\path\\to\\forward.xml" /></label><div className="trl-m0__actions"><input ref={forwardRef} className="trl-m0__file-input" type="file" accept=".xml" onChange={onForwardSelect} /><button type="button" onClick={() => forwardRef.current?.click()}>Browse forward XML…</button></div>
    <div className="trl-m0__scenario-fields">
      <label className="trl-m0__field"><span>In-sample start — USER_SUPPLIED</span><input type="date" value={inStart} onChange={(event) => onInStartChange(event.currentTarget.value)} /></label>
      <label className="trl-m0__field"><span>In-sample end — USER_SUPPLIED</span><input type="date" value={inEnd} onChange={(event) => onInEndChange(event.currentTarget.value)} /></label>
      <label className="trl-m0__field"><span>Forward start — USER_SUPPLIED</span><input type="date" value={forwardStart} onChange={(event) => onForwardStartChange(event.currentTarget.value)} /></label>
      <label className="trl-m0__field"><span>Forward end — USER_SUPPLIED</span><input type="date" value={forwardEnd} onChange={(event) => onForwardEndChange(event.currentTarget.value)} /></label>
    </div>
    <label className="trl-m0__field"><span>Modelling mode — USER_SUPPLIED</span><input value={mode} onChange={(event) => onModeChange(event.currentTarget.value)} placeholder="For example: Open prices only" /></label>
    <p className="trl-m0__note">The XML does not establish these facts. They are preserved as your declared context and must be contiguous for a strict pair.</p>
    <button type="button" className="mod-cta" disabled={!inPath.toLowerCase().endsWith(".xml") || !forwardPath.toLowerCase().endsWith(".xml") || !inStart || !inEnd || !forwardStart || !forwardEnd || !mode.trim()} onClick={onRun}>Import paired forward evidence</button>
    {result && <section className="trl-m0__analysis-result"><h4>Complete paired source evidence</h4><dl className="trl-m0__diagnostic-grid"><dt>Pairs</dt><dd>{result.pair_count} complete parameter signatures</dd><dt>In-sample / forward source</dt><dd><code>{result.in_sample_source.filename}</code> / <code>{result.forward_source.filename}</code></dd><dt>Context</dt><dd>{result.context.in_sample_start} to {result.context.in_sample_end}; forward {result.context.forward_start} to {result.context.forward_end}; <code>{result.context.modelling_mode}</code> — {result.context.modelling_mode_source}</dd><dt>Artifact</dt><dd><code>{result.artifacts.table}</code></dd><dt>Warnings</dt><dd>{result.warnings.join(" ")}</dd></dl><div className="trl-m0__optimisation-table"><table><thead><tr>{headers.map((header) => <th key={header}>{header}</th>)}</tr></thead><tbody>{result.rows.map((row) => <tr key={row.trl_parameter_signature}>{headers.map((header) => <td key={header}>{row[header]}</td>)}</tr>)}</tbody></table></div><p className="trl-m0__note">No table ranking is shown in this first slice. The Core preserved paired evidence for inspected comparison only.</p></section>}
  </CollapsibleSection>;
}
